version: '3'
services:
  jenkins-master:
    build: jenkins-master
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/jenkins_home:/var/jenkins_home"

  artifactory:
    container_name: artifactory_named
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    ports:
      - "8081:8081"
    volumes:
      - "/var/opt/jfrog/artifactory:/var/opt/jfrog/artifactory"
